import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import { Dialog } from '@reach/dialog'
import { GetStaticProps, InferGetStaticPropsType } from 'next';


type TDataList_User = {
  // name: string
  id: string
  email: string
  first_name: string
  last_name: string
  avatar: string

}

export const getStaticProps: GetStaticProps<{ dataList_User: TDataList_User[] }> = async (content) => {
  const _res = await fetch('https://reqres.in/api/users')
  const _data: any = await _res.json()
  console.log('_data: ', _data);

  const data = _data.data as TDataList_User[]

  return {
    props: {
      dataList_User: data,
    }
  }

}

export default function Home({ dataList_User }: InferGetStaticPropsType<typeof getStaticProps>) {

  const [data_canShow, setData_canShow] = useState<boolean>(false)


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

<section>
  {
    dataList_User.map((_item, index) => {
      return (
        <p key={index}>{ _item.first_name}&nbsp;{_item.last_name}</p>
      )
    })
  }
</section>
<div>
      Hello world
      <p>scoped!</p>
      <style jsx>{`
        p {
          color: blue;
        }
        div {
          background: red;
        }
        @media (max-width: 600px) {
          div {
            background: blue;
          }
        }
      `}</style>
      <style global jsx>{`
        body {
          background: black;
        }
      `}</style>
    </div>
        <div>

          <button
          className='bg-blue-400 text-white py-1 px-2 rounded'
          onClick={() => {
            setData_canShow(!data_canShow)
          }}>按我</button>
        </div>

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            {
              data_canShow ? <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> : <div>image hide</div>
            }

          </span>
        </a>
      </footer>
    </div>
  )
}



